In [1]:
import math
from tensorboardX import SummaryWriter
import env_configurations
import tensorflow as tf
import collections
import gym
import wrappers
import games_configurations
from validator import Validator

a2c_config = games_configurations.animal_ai_ray
gpu_options = tf.GPUOptions(allow_growth=True,per_process_gpu_memory_fraction=0.8)

config=tf.ConfigProto(gpu_options=gpu_options)
sess = tf.InteractiveSession(config=config)

In [2]:
#validator = Validator(sess, a2c_config, 'nn/animal84_5AnimalAI')
validator = Validator(sess, a2c_config, 'nn/animal84AnimalAIRay')
print('normalized score: ', validator.run())

W0820 07:42:56.765953 139620787271488 deprecation_wrapper.py:119] From /home/trrrrr/Documents/github/ml/rl_animal/players.py:95: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0820 07:42:56.769957 139620787271488 deprecation_wrapper.py:119] From /home/trrrrr/Documents/github/ml/rl_animal/networks.py:259: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

W0820 07:42:56.770392 139620787271488 deprecation.py:323] From /home/trrrrr/Documents/github/ml/rl_animal/networks.py:207: conv2d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.keras.layers.Conv2D` instead.
W0820 07:42:56.773066 139620787271488 deprecation.py:506] From /home/trrrrr/anaconda3/envs/rl/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will b

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
shapes of layer_1 [None, 42, 42, 16]
shapes of layer_2 [None, 21, 21, 32]
shapes of layer_3 [None, 11, 11, 64]
shapes of layer_4 [None, 6, 6, 128]


W0820 07:42:57.431260 139620787271488 lazy_loader.py:50] 
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

W0820 07:42:57.431946 139620787271488 deprecation.py:323] From /home/trrrrr/anaconda3/envs/rl/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py:1634: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.flatten instead.
W0820 07:42:57.625879 139620787271488 deprecation.py:323] From /home/trrrrr/Documents/github/ml/rl_animal/networks.py:265: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for u

0


W0820 07:42:58.698076 139620787271488 deprecation.py:323] From /home/trrrrr/anaconda3/envs/rl/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.


WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
starting:  /home/trrrrr/Documents/github/ml/rl_animal/validation/1-Food.yaml
/home/trrrrr/Documents/github/ml/rl_animal/validation/1-Food.yaml reward:  247.51834815274924
c_looses:  4
starting:  /home/trrrrr/Documents/github/ml/rl_animal/validation/2-Preferences.yaml
/home/trrrrr/Documents/github/ml/rl_animal/validation/2-Preferences.yaml reward:  403.39577344805
c_looses:  0
starting:  /home/trrrrr/Documents/github/ml/rl_animal/validation/3-Obstacles.yaml
/home/trrrrr/Documents/github/ml/rl_animal/validation/3-Obstacles.yaml reward:  49.05500124394894
c_looses:  15
starting:  /home/trrrrr/Documents/github/ml/rl_animal/validation/4-Avoidance.yaml
/home/trrrrr/Documents/github/ml/rl_animal/validation/4-Avoidance.yaml reward:  3.2240021023899317
c_looses:  40
starting:  /home/trrrrr/Documents/github/ml/rl_animal/validation/5-SpatialReasoning.yaml
/home/trrrrr/Documents/github/ml/rl_animal/v

In [2]:

import numpy as np
import players
ppo_player = players.PpoPlayerDiscrete(sess, a2c_config)
env = ppo_player.create_env()
#ppo_player.restore('nn/stages_allAnimalAI')
#ppo_player = players.PpoPlayerDiscrete(sess, a2c_config)
#ppo_player.restore('nn/stages_allAnimalAI')
ppo_player.restore('nn/animal84AnimalAIRay')

W0825 10:07:38.512876 139620787271488 deprecation_wrapper.py:119] From /home/trrrrr/Documents/github/ml/rl_animal/players.py:95: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0825 10:07:38.516989 139620787271488 deprecation_wrapper.py:119] From /home/trrrrr/Documents/github/ml/rl_animal/networks.py:259: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

W0825 10:07:38.517513 139620787271488 deprecation.py:323] From /home/trrrrr/Documents/github/ml/rl_animal/networks.py:207: conv2d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.keras.layers.Conv2D` instead.
W0825 10:07:38.520312 139620787271488 deprecation.py:506] From /home/trrrrr/anaconda3/envs/rl/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will b

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
shapes of layer_1 [None, 42, 42, 16]
shapes of layer_2 [None, 21, 21, 32]
shapes of layer_3 [None, 11, 11, 64]
shapes of layer_4 [None, 6, 6, 128]


W0825 10:07:39.153565 139620787271488 lazy_loader.py:50] 
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

W0825 10:07:39.154146 139620787271488 deprecation.py:323] From /home/trrrrr/anaconda3/envs/rl/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py:1634: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.flatten instead.
W0825 10:07:39.297490 139620787271488 deprecation.py:323] From /home/trrrrr/Documents/github/ml/rl_animal/networks.py:265: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for u

0


W0825 10:07:44.010099 139620787271488 deprecation.py:323] From /home/trrrrr/anaconda3/envs/rl/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.


WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.


In [3]:
import time
vels = []
time.sleep(2)
ppo_player.reset()
def evaluate(env,t_max=5000):
    rewards = []
    #env._max_episode_steps = 5000
    env.batch_mode = False
    print('reset')
    #env = env.old_env
    s = env.reset()
    
    
    reward = 0
    for it in range(5000):
        vels.append([s[1]])
        print(s[1])
        action = ppo_player.get_action(s, True)
        s, r, done, _ = env.step(action)
        time.sleep( 0.01 )
        #print(action)
        env.render()
        reward += r
        
            
        if done:
            break       
    time.sleep(1.0)
    return reward

import gym.wrappers

#env_monitor = wrappers.make_atari_deepmind(env_name, noop_max=30, skip=4)
#env_monitor = wrappers.ReallyDoneWrapper(env_monitor)
env = gym.wrappers.Monitor(env,directory='video_ppo',force=True)

sessions = [print('reward:', evaluate(env)) for _ in range(10)]
env.close()

WARN: Trying to monitor an environment which has no 'spec' set. This usually means you did not create it via 'gym.make', and is recommended only for advanced users.
reset
[0. 0. 0. 0. 0. 0.]
[ 0.          0.          0.          0.00209398 -0.13568877  0.05996347]
[ 0.00209398 -0.13568877  0.05996347  0.00212966 -0.00385761  0.01515325]
[ 2.12965673e-03 -3.85761261e-03  1.51532535e-02  1.29998401e-02
 -3.09944153e-05  1.64809793e-01]
[ 1.29998401e-02 -3.09944153e-05  1.64809793e-01  3.57243568e-02
  0.00000000e+00  2.96074033e-01]
[0.03572436 0.         0.29607403 0.02988549 0.         0.41456413]
[0.02988549 0.         0.41456413 0.02531736 0.         0.51935375]
[0.02531736 0.         0.51935375 0.05475053 0.         0.26219922]
[0.05475053 0.         0.26219922 0.04558668 0.         0.38472492]
[0.04558668 0.         0.38472492 0.03852209 0.         0.4930042 ]
[ 0.03852209  0.          0.4930042  -0.02282061  0.          0.58942926]
[-0.02282061  0.          0.58942926 -0.01954228 

[0.00655508 0.         0.07809754 0.02234576 0.         0.22033693]
[0.02234576 0.         0.22033693 0.03587959 0.         0.17188169]
[0.03587959 0.         0.17188169 0.0412469  0.         0.12853876]
[0.0412469  0.         0.12853876 0.03996945 0.         0.09066158]
[0.03996945 0.         0.09066158 0.0334408  0.         0.05841225]
[0.0334408  0.         0.05841225 0.02292295 0.         0.03179397]
[ 0.02292295  0.          0.03179397  0.00668997  0.         -0.12718306]
[ 0.00668997  0.         -0.12718306 -0.00481422  0.         -0.09220008]
[-0.00481422  0.         -0.09220008 -0.00243688  0.          0.08393247]
[-0.00243688  0.          0.08393247  0.00407875  0.          0.05378161]
[0.00407875 0.         0.05378161 0.00491045 0.         0.02692168]
[0.00491045 0.         0.02692168 0.         0.         0.        ]
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[ 0.          0.          0.         -0.01015973  0.         -0.15213922]
[-0.01015973  0.         -

[-0.03034226  0.         -0.18692903 -0.03864188  0.         -0.14203134]
[-0.03864188  0.         -0.14203134 -0.03976884  0.         -0.10242489]
[-0.03976884  0.         -0.10242489 -0.03515472  0.         -0.0683454 ]
[-0.03515472  0.         -0.0683454  -0.02043241  0.          0.10041773]
[-0.02043241  0.          0.10041773 -0.00674039  0.          0.0699865 ]
[-0.00674039  0.          0.0699865   0.01130863  0.          0.2142978 ]
[0.01130863 0.         0.2142978  0.02657741 0.         0.16741094]
[0.02657741 0.         0.16741094 0.03359243 0.         0.12518732]
[0.03359243 0.         0.12518732 0.04840018 0.         0.25965667]
[0.04840018 0.         0.25965667 0.06079927 0.         0.20448381]
[0.06079927 0.         0.20448381 0.06459917 0.         0.15550436]
[0.06459917 0.         0.15550436 0.06149108 0.         0.1129756 ]
[ 0.06149108  0.          0.1129756   0.03780706  0.         -0.07320757]
[ 0.03780706  0.         -0.07320757  0.01909794  0.         -0.0489497 ]


[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0.         0.         0.         0.01015972 0.         0.15213922]
[0.01015972 0.         0.15213922 0.03222721 0.         0.28516808]
[0.03222721 0.         0.28516808 0.0353471  0.         0.05678513]
[0.0353471  0.         0.05678513 0.02385    0.         0.03063547]
[0.02385    0.         0.03063547 0.01781245 0.         0.17995571]
[0.01781245 0.         0.17995571 0.04107914 0.         0.3090021 ]
[0.04107914 0.         0.3090021  0.03442656 0.         0.42602   ]
[ 0.03442656  0.          0.42602    -0.00861671  0.          0.35768682]
[-0.00861671  0.          0.35768682 -0.00726062  0.          0.46900427]
[-0.00726062  0.          0.46900427  0.02317999  0.          0.2206645 ]
[0.02317999 0.         0.2206645  0.01914087 0.         0.34781969]
[0.01914087 0.         0.34781969 0.01611209 0.         0.46028817]
[ 0.01611209  0.          0.46028817 -0.02697254  0.          0.38618883]
[-0.02697254  0.          0.38618883 -0.02244548  0.

[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[ 0.          0.          0.          0.          0.         -0.15254268]
[ 0.          0.         -0.15254268  0.02407445  0.         -0.28637558]
[ 0.02407445  0.         -0.28637558 -0.00487688  0.         -0.23385626]
[-0.00487688  0.         -0.23385626 -0.02336919  0.         -0.18512356]
[-0.02336919  0.         -0.18512356 -0.03303671  0.         -0.14091106]
[-0.03303671  0.         -0.14091106 -0.03540837  0.         -0.10170908]
[-0.03540837  0.         -0.10170908 -0.0246353   0.         -0.07076388]
[-0.0246353   0.         -0.07076388 -0.01955627  0.         -0.04156907]
[-0.01955627  0.         -0.04156907 -0.01050969  0.         -0.01735714]
[-1.05096884e-02  0.00000000e+00 -1.73571408e-02 -8.36469075e-19
  0.00000000e+00  2.29425471e-19]
[-8.36469075e-19  0.00000000e+00  2.29425471e-19  0.00000000e+00
  0.00000000e+00  0.00000000e+00]
[0. 0. 0. 0. 0. 0.]
[ 0.          0.          0.         -0.01015972  0.    

[-0.00231093  0.          0.09323713  0.01682393  0.          0.23438314]
[ 0.01682393  0.          0.23438314 -0.00619984  0.          0.18744496]
[-0.00619984  0.          0.18744496 -0.00507855  0.          0.31838623]
[-0.00507855  0.          0.31838623 -0.03146292  0.          0.25946954]
[-0.03146292  0.          0.25946954 -0.02617345  0.          0.38217422]
[-0.02617345  0.          0.38217422 -0.02210924  0.          0.49069324]
[-0.02210924  0.          0.49069324  0.02471152  0.          0.41348341]
[0.02471152 0.         0.41348341 0.02093194 0.         0.51838797]
[0.02093194 0.         0.51838797 0.01785922 0.         0.61119002]
[0.01785922 0.         0.61119002 0.01530853 0.         0.69329053]
[0.01530853 0.         0.69329053 0.01316443 0.         0.76592523]
[0.01316443 0.         0.76592523 0.01134723 0.         0.83018655]
[0.01134723 0.         0.83018655 0.0097611  0.         0.71414441]
[0.0097611  0.         0.71414441 0.00840002 0.         0.78437334]
[0.008

[-0.2500633   0.          0.43663418 -0.21112491  0.          0.36864406]
[-0.21112491  0.          0.36864406 -0.14346072  0.          0.32526836]
[-0.14346072  0.          0.32526836 -0.09748355  0.          0.10987253]
[-0.09748355  0.          0.10987253 -0.06377109  0.          0.0891377 ]
[-0.06377109  0.          0.0891377  -0.0378206   0.          0.06662839]
[-0.0378206   0.          0.06662839 -0.01897396  0.          0.04346951]
[-0.01897396  0.          0.04346951 -0.00652721  0.          0.02060041]
[-6.52721105e-03  0.00000000e+00  2.06004120e-02  1.45693180e-12
  0.00000000e+00  2.60308497e-10]
[1.45693180e-12 0.00000000e+00 2.60308497e-10 6.06871293e-33
 0.00000000e+00 5.47882518e-32]
[ 6.06871293e-33  0.00000000e+00  5.47882518e-32 -7.45058060e-09
  0.00000000e+00  1.52542666e-01]
[-7.45058060e-09  0.00000000e+00  1.52542666e-01  2.40745246e-02
  0.00000000e+00  2.86375523e-01]
[0.02407452 0.         0.28637552 0.0438513  0.         0.22975986]
[0.0438513  0.         0

[0.04763579 0.         0.97018343 0.04126325 0.         1.0109179 ]
[ 0.04126325  0.          1.0109179  -0.04403874  0.          0.70058084]
[-0.04403874  0.          0.70058084 -0.03788184  0.          0.77240062]
[-0.03788184  0.          0.77240062 -0.03265965  0.          0.83593148]
[-0.03265965  0.          0.83593148 -0.02820593  0.          0.892133  ]
[-0.02820593  0.          0.892133   -0.10455678  0.          0.76220524]
[-0.10455678  0.          0.76220524 -0.16997194  0.          0.81353372]
reward: 1.7295077154412866


In [ ]:
print(np.mean(vels))
print(np.std(vels))