In [1]:
import math
from tensorboardX import SummaryWriter
import env_configurations
import tensorflow as tf
import collections
import gym
import wrappers
import games_configurations
from validator import Validator

a2c_config = games_configurations.animal_ai
gpu_options = tf.GPUOptions(allow_growth=True,per_process_gpu_memory_fraction=0.8)

config=tf.ConfigProto(gpu_options=gpu_options)
sess = tf.InteractiveSession(config=config)

In [2]:
#validator = Validator(sess, a2c_config, 'nn/animal84_5AnimalAI')
validator = Validator(sess, a2c_config, 'nn/last84_an15')
print('normalized score: ', validator.run())

W0820 07:42:56.765953 139620787271488 deprecation_wrapper.py:119] From /home/trrrrr/Documents/github/ml/rl_animal/players.py:95: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0820 07:42:56.769957 139620787271488 deprecation_wrapper.py:119] From /home/trrrrr/Documents/github/ml/rl_animal/networks.py:259: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

W0820 07:42:56.770392 139620787271488 deprecation.py:323] From /home/trrrrr/Documents/github/ml/rl_animal/networks.py:207: conv2d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.keras.layers.Conv2D` instead.
W0820 07:42:56.773066 139620787271488 deprecation.py:506] From /home/trrrrr/anaconda3/envs/rl/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will b

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
shapes of layer_1 [None, 42, 42, 16]
shapes of layer_2 [None, 21, 21, 32]
shapes of layer_3 [None, 11, 11, 64]
shapes of layer_4 [None, 6, 6, 128]


W0820 07:42:57.431260 139620787271488 lazy_loader.py:50] 
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

W0820 07:42:57.431946 139620787271488 deprecation.py:323] From /home/trrrrr/anaconda3/envs/rl/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py:1634: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.flatten instead.
W0820 07:42:57.625879 139620787271488 deprecation.py:323] From /home/trrrrr/Documents/github/ml/rl_animal/networks.py:265: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for u

0


W0820 07:42:58.698076 139620787271488 deprecation.py:323] From /home/trrrrr/anaconda3/envs/rl/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.


WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
starting:  /home/trrrrr/Documents/github/ml/rl_animal/validation/1-Food.yaml
/home/trrrrr/Documents/github/ml/rl_animal/validation/1-Food.yaml reward:  247.51834815274924
c_looses:  4
starting:  /home/trrrrr/Documents/github/ml/rl_animal/validation/2-Preferences.yaml
/home/trrrrr/Documents/github/ml/rl_animal/validation/2-Preferences.yaml reward:  403.39577344805
c_looses:  0
starting:  /home/trrrrr/Documents/github/ml/rl_animal/validation/3-Obstacles.yaml
/home/trrrrr/Documents/github/ml/rl_animal/validation/3-Obstacles.yaml reward:  49.05500124394894
c_looses:  15
starting:  /home/trrrrr/Documents/github/ml/rl_animal/validation/4-Avoidance.yaml
/home/trrrrr/Documents/github/ml/rl_animal/validation/4-Avoidance.yaml reward:  3.2240021023899317
c_looses:  40
starting:  /home/trrrrr/Documents/github/ml/rl_animal/validation/5-SpatialReasoning.yaml
/home/trrrrr/Documents/github/ml/rl_animal/v

In [2]:

import numpy as np
import players
ppo_player = players.PpoPlayerDiscrete(sess, a2c_config)
env = ppo_player.create_env()
#ppo_player.restore('nn/stages_allAnimalAI')
#ppo_player = players.PpoPlayerDiscrete(sess, a2c_config)
#ppo_player.restore('nn/stages_allAnimalAI')
ppo_player.restore('nn/last84_an14')

W0819 08:42:54.063847 139620787271488 deprecation_wrapper.py:119] From /home/trrrrr/Documents/github/ml/rl_animal/players.py:95: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

W0819 08:42:54.067781 139620787271488 deprecation_wrapper.py:119] From /home/trrrrr/Documents/github/ml/rl_animal/networks.py:259: The name tf.variable_scope is deprecated. Please use tf.compat.v1.variable_scope instead.

W0819 08:42:54.068270 139620787271488 deprecation.py:323] From /home/trrrrr/Documents/github/ml/rl_animal/networks.py:207: conv2d (from tensorflow.python.layers.convolutional) is deprecated and will be removed in a future version.
Instructions for updating:
Use `tf.keras.layers.Conv2D` instead.
W0819 08:42:54.070910 139620787271488 deprecation.py:506] From /home/trrrrr/anaconda3/envs/rl/lib/python3.6/site-packages/tensorflow/python/ops/init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will b

WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.
shapes of layer_1 [None, 42, 42, 16]
shapes of layer_2 [None, 21, 21, 32]
shapes of layer_3 [None, 11, 11, 64]
shapes of layer_4 [None, 6, 6, 128]


W0819 08:42:54.711805 139620787271488 lazy_loader.py:50] 
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

W0819 08:42:54.712330 139620787271488 deprecation.py:323] From /home/trrrrr/anaconda3/envs/rl/lib/python3.6/site-packages/tensorflow/contrib/layers/python/layers/layers.py:1634: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.flatten instead.
W0819 08:42:54.855554 139620787271488 deprecation.py:323] From /home/trrrrr/Documents/github/ml/rl_animal/networks.py:265: dense (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for u

0


W0819 08:42:59.011989 139620787271488 deprecation.py:323] From /home/trrrrr/anaconda3/envs/rl/lib/python3.6/site-packages/tensorflow/python/training/saver.py:1276: checkpoint_exists (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file APIs to check for files with this prefix.


WARN: gym.spaces.Box autodetected dtype as <class 'numpy.float32'>. Please provide explicit dtype.


In [3]:
import time
vels = []
time.sleep(2)
ppo_player.reset()
def evaluate(env,t_max=5000):
    rewards = []
    #env._max_episode_steps = 5000
    env.batch_mode = False
    print('reset')
    #env = env.old_env
    s = env.reset()
    
    
    reward = 0
    for it in range(5000):
        vels.append([s[1]])
        print(s[1])
        action = ppo_player.get_action(s, True)
        s, r, done, _ = env.step(action)
        time.sleep( 0.01 )
        #print(action)
        env.render()
        reward += r
        
            
        if done:
            break       
    time.sleep(1.0)
    return reward

import gym.wrappers

#env_monitor = wrappers.make_atari_deepmind(env_name, noop_max=30, skip=4)
#env_monitor = wrappers.ReallyDoneWrapper(env_monitor)
env = gym.wrappers.Monitor(env,directory='video_ppo',force=True)

sessions = [print('reward:', evaluate(env)) for _ in range(10)]
env.close()

WARN: Trying to monitor an environment which has no 'spec' set. This usually means you did not create it via 'gym.make', and is recommended only for advanced users.
reset
[0. 0. 0. 0. 0. 0.]
[ 0.          0.          0.          0.00574399 -0.08849561  0.11035374]
[ 0.00574399 -0.08849561  0.11035374  0.02322602 -0.00070751  0.23723868]
[ 2.32260171e-02 -7.07507133e-04  2.37238675e-01  5.09880781e-02
 -5.36441803e-06  3.58833313e-01]
[ 5.09880781e-02 -5.36441803e-06  3.58833313e-01 -3.38613987e-04
 -5.96046448e-07  4.72512096e-01]
[-3.38613987e-04 -5.96046448e-07  4.72512096e-01 -5.38499802e-02
  0.00000000e+00  5.67892373e-01]
[-5.38499802e-02  0.00000000e+00  5.67892373e-01 -4.60705757e-02
 -5.96046448e-07  6.55038714e-01]
[-4.60705757e-02 -5.96046448e-07  6.55038714e-01  3.10777575e-02
  0.00000000e+00  7.32702971e-01]
[ 3.10777575e-02  0.00000000e+00  7.32702971e-01  1.04212105e-01
 -5.96046448e-07  7.94078231e-01]
[ 1.04212105e-01 -5.96046448e-07  7.94078231e-01  6.14015758e-03
  

[-0.06027742  0.         -0.12559575 -0.0539763   0.         -0.08760746]
[-0.0539763   0.         -0.08760746 -0.04316598  0.         -0.0559756 ]
[-0.04316598  0.         -0.0559756  -0.02911215  0.         -0.03053031]
[-0.02911215  0.         -0.03053031 -0.01293036  0.         -0.01098986]
[-0.01293036  0.         -0.01098986  0.          0.          0.        ]
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0.]
[0.0000000e+00 0.0000000e+00 0.0000000e+00 7.4505806e-09 0.0000000e+00
 1.5254271e-01]
[ 7.45058060e-09  0.00000000e+00  1.52542710e-01  2.29889713e-03
  0.00000000e+00 -4.55482006e-02]
[ 0.0022989   0.         -0.0455482   0.00100796  0.         -0.01997069]
[ 0.00100796  0.         -0.01997069  0.00901409  0.          0.1344948 ]
[0.00901409 0.         0.1344948  0.02963634 0.         0.2697427 ]
[0.02963634 0.         0.2697427  0.02469452 0.         0.39125216]
[0.02469452 0.         0.39125216 0.02087724 0.         0.49872094]
[0.02087724 

[-0.04532224  0.          1.21485341 -0.03941208  0.          1.22737885]
[-0.03941208  0.          1.22737885 -0.03427804  0.          1.23845744]
[-0.03427804  0.          1.23845744 -0.02981699  0.          1.24825692]
reward: 2.1668500900268555
reset
[0. 0. 0. 0. 0. 0.]
[ 0.          0.          0.          0.00184692 -0.08849621  0.05288889]
[ 0.00184692 -0.08849621  0.05288889  0.01503285 -0.0007081   0.18697324]
[ 1.50328502e-02 -7.08103180e-04  1.86973244e-01  3.94713879e-02
 -4.76837158e-06  3.15310329e-01]
[ 3.94713879e-02 -4.76837158e-06  3.15310329e-01  7.19880760e-02
  0.00000000e+00  4.26209927e-01]
[0.07198808 0.         0.42620993 0.11002971 0.         0.52095747]
[0.11002971 0.         0.52095747 0.03535971 0.         0.62067139]
[0.03535971 0.         0.62067139 0.09740476 0.         0.69513762]
[0.09740476 0.         0.69513762 0.00918528 0.         0.77271837]
[ 0.00918528  0.          0.77271837 -0.07341903  0.          0.83290327]
[-0.07341903  0.          0.83290

[-1.52700946e-01  0.00000000e+00 -2.79283851e-01 -1.48610890e-01
 -5.96046448e-07 -2.14877248e-01]
[-1.48610890e-01 -5.96046448e-07 -2.14877248e-01 -1.37369215e-01
  0.00000000e+00 -1.59886599e-01]
[-1.37369215e-01  0.00000000e+00 -1.59886599e-01  0.00000000e+00
 -1.19209290e-07  0.00000000e+00]
[ 0.0000000e+00 -1.1920929e-07  0.0000000e+00  0.0000000e+00
 -1.1920929e-07  0.0000000e+00]
[ 0.00000000e+00 -1.19209290e-07  0.00000000e+00  0.00000000e+00
 -5.96046448e-07  0.00000000e+00]
[ 0.00000000e+00 -5.96046448e-07  0.00000000e+00  0.00000000e+00
 -5.96046448e-07  0.00000000e+00]
[ 0.00000000e+00 -5.96046448e-07  0.00000000e+00  1.01597086e-02
  0.00000000e+00  1.52139157e-01]
[ 1.01597086e-02  0.00000000e+00  1.52139157e-01  3.22272032e-02
 -5.96046448e-07  2.85168111e-01]
[ 3.22272032e-02 -5.96046448e-07  2.85168111e-01  6.30540997e-02
  0.00000000e+00  4.00316596e-01]
[ 6.30540997e-02  0.00000000e+00  4.00316596e-01  9.99844968e-02
 -5.96046448e-07  4.98952508e-01]
[ 9.99844968e-02

reward: 3.348484992980957
reset
[0. 0. 0. 0. 0. 0.]
[ 0.          0.          0.          0.00184693 -0.08849621  0.05288889]
[ 0.00184693 -0.08849621  0.05288889  0.01503286 -0.0007081   0.18697321]
[ 1.50328577e-02 -7.08103180e-04  1.86973214e-01  3.94714028e-02
 -4.76837158e-06  3.15310270e-01]
[ 3.94714028e-02 -4.76837158e-06  3.15310270e-01  7.19879866e-02
  0.00000000e+00  4.26209867e-01]
[0.07198799 0.         0.42620987 0.11002961 0.         0.52095723]
[0.11002961 0.         0.52095723 0.1514865  0.         0.60100424]
[0.1514865  0.         0.60100424 0.19463782 0.         0.66781807]
[0.19463782 0.         0.66781807 0.09478995 0.         0.75786662]
[0.09478995 0.         0.75786662 0.00131658 0.         0.82766825]
[ 0.00131658  0.          0.82766825 -0.08524182  0.          0.88054323]
reward: 2.8190152645111084


In [ ]:
print(np.mean(vels))
print(np.std(vels))